name: SkyAboveTheSky
favicon: null
layout_spectrum: 0.85309
typography_spectrum: 0.55657
title: 'Spin Echo | Sky above The Sky | Inspiration & Creation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001534'
    - '#0065b7'
    - '#8488ec'
    - '#b58557'
    - '#d2deae'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
